// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRN232.LMS.Course.API.Infrastructure.Data;

#nullable disable

namespace PRN232.LMS.Course.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    partial class CourseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRN232.LMS.Course.API.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Courseid"));

                    b.Property<string>("Coursename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Semesterid")
                        .HasColumnType("integer");

                    b.HasKey("Courseid");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("PRN232.LMS.Course.API.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("Enrollmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Enrollmentid"));

                    b.Property<int>("Courseid")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Enrolldate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer");

                    b.HasKey("Enrollmentid");

                    b.HasIndex("Courseid");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("PRN232.LMS.Course.API.Domain.Entities.Grade", b =>
                {
                    b.Property<int>("Gradeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Gradeid"));

                    b.Property<int>("Enrollmentid")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Mark")
                        .HasColumnType("numeric");

                    b.Property<int>("Subjectid")
                        .HasColumnType("integer");

                    b.HasKey("Gradeid");

                    b.HasIndex("Enrollmentid");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("PRN232.LMS.Course.API.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("PRN232.LMS.Course.API.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("PRN232.LMS.Course.API.Domain.Entities.Grade", b =>
                {
                    b.HasOne("PRN232.LMS.Course.API.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany("Grades")
                        .HasForeignKey("Enrollmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("PRN232.LMS.Course.API.Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("PRN232.LMS.Course.API.Domain.Entities.Enrollment", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
