// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRN232.LMS.Student.API.Infrastructure.Data;

#nullable disable

namespace PRN232.LMS.Student.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRN232.LMS.Student.API.Domain.Entities.Semester", b =>
                {
                    b.Property<int>("Semesterid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Semesterid"));

                    b.Property<DateOnly>("Enddate")
                        .HasColumnType("date");

                    b.Property<string>("Semestername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Startdate")
                        .HasColumnType("date");

                    b.HasKey("Semesterid");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("PRN232.LMS.Student.API.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Studentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Studentid"));

                    b.Property<DateOnly?>("Dateofbirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Studentid");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PRN232.LMS.Student.API.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Subjectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Subjectid"));

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<string>("Subjectcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subjectname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Subjectid");

                    b.ToTable("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
