// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRN232.LMS.Models.Entities;

#nullable disable

namespace PRN232.LMS.Models.Migrations
{
    [DbContext(typeof(LmsdbContext))]
    [Migration("20260530092816_AddAuthTable")]
    partial class AddAuthTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseSubject", b =>
                {
                    b.Property<int>("CoursesCourseid")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectsSubjectid")
                        .HasColumnType("integer");

                    b.HasKey("CoursesCourseid", "SubjectsSubjectid");

                    b.HasIndex("SubjectsSubjectid");

                    b.ToTable("CourseSubject");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Course", b =>
                {
                    b.Property<int>("Courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Courseid"));

                    b.Property<string>("Coursename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Semesterid")
                        .HasColumnType("integer");

                    b.HasKey("Courseid");

                    b.HasIndex("Semesterid");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Enrollment", b =>
                {
                    b.Property<int>("Enrollmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Enrollmentid"));

                    b.Property<int>("Courseid")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Enrolldate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer");

                    b.HasKey("Enrollmentid");

                    b.HasIndex("Courseid");

                    b.HasIndex("Studentid");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Grade", b =>
                {
                    b.Property<int>("Gradeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Gradeid"));

                    b.Property<int>("Enrollmentid")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Mark")
                        .HasColumnType("numeric");

                    b.Property<int>("Subjectid")
                        .HasColumnType("integer");

                    b.HasKey("Gradeid");

                    b.HasIndex("Enrollmentid");

                    b.HasIndex("Subjectid");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Semester", b =>
                {
                    b.Property<int>("Semesterid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Semesterid"));

                    b.Property<DateOnly>("Enddate")
                        .HasColumnType("date");

                    b.Property<string>("Semestername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Startdate")
                        .HasColumnType("date");

                    b.HasKey("Semesterid");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Student", b =>
                {
                    b.Property<int>("Studentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Studentid"));

                    b.Property<DateOnly?>("Dateofbirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Studentid");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Subject", b =>
                {
                    b.Property<int>("Subjectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Subjectid"));

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<string>("Subjectcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subjectname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Subjectid");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CourseSubject", b =>
                {
                    b.HasOne("PRN232.LMS.Models.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN232.LMS.Models.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsSubjectid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Course", b =>
                {
                    b.HasOne("PRN232.LMS.Models.Entities.Semester", "Semester")
                        .WithMany("Courses")
                        .HasForeignKey("Semesterid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Enrollment", b =>
                {
                    b.HasOne("PRN232.LMS.Models.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN232.LMS.Models.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Grade", b =>
                {
                    b.HasOne("PRN232.LMS.Models.Entities.Enrollment", "Enrollment")
                        .WithMany("Grades")
                        .HasForeignKey("Enrollmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN232.LMS.Models.Entities.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("Subjectid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("PRN232.LMS.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Enrollment", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Semester", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.Subject", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("PRN232.LMS.Models.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
